
# 数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.3.200:3306/mybatis-test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: mysql
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 2
      minIdle: 3
      maxActive: 5
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000

mybatis-plus:
  config-location: classpath:mybatis-config.xml
#  type-aliases-package: com.uptoser.cashbook.entities
  mapper-locations: classpath:com/uptoser/springboot/learning/**/mapper/xml/*Mapper.xml

swagger:
  title: 接口文档
  description: 接口
  exclude-path: /actuator/**,${server.servlet.context-path}/error # 剔除请求
  authorization:
    key-name: Authorization-Token