
# 数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.3.200:3306/mybatis-test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: mysql
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 2
      minIdle: 3
      maxActive: 5
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mapper/**/*Mapper.xml

