spring:
  profiles:
    active: dev
  application:
    name: springboot
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8080
  servlet:
    context-path: /springboot

# 自定义的属性值
property-values :
  email: "Ming@abc.com \n Hello"
  age: 22
  salary: 10000
  map: {a: 1,b: 2,c: Three}
  list:
    - 1
    - java
    - 2
    - c++




