spring:
  profiles:
    active: dev
  application:
    name: springboot
  # 格式化Date日期对象，如果格式化LocalDateTime需要配置Json序列化器
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null # 不处理空值

server:
  port: 8080
  servlet:
    context-path: /springboot

# 自定义的属性值
property-values :
  email: "Ming@abc.com \n Hello"
  age: 22
  salary: 10000
  map: {a: 1,b: 2,c: Three}
  list:
    - 1
    - java
    - 2
    - c++




